//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntercambioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Participantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Participantes()
        {
            this.Sorteo = new HashSet<Sorteo>();
            this.Sorteo1 = new HashSet<Sorteo>();
            this.Sugerencias = new HashSet<Sugerencias>();
        }
    
        public string IdPart { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Sexo { get; set; }
        public string Grado { get; set; }
        public string Grupo { get; set; }
        public string Area { get; set; }
        public string Gustos { get; set; }
        public string IdUsuario { get; set; }
        public string OpcionesIntercambio { get; set; }
    
        public virtual Asistencia Asistencia { get; set; }
        public virtual Usuarios Usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorteo> Sorteo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sorteo> Sorteo1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sugerencias> Sugerencias { get; set; }
    }
}
