//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntercambioAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorteo
    {
        public string IdPart1 { get; set; }
        public string IdPartInter { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
    
        public virtual Participantes Participantes { get; set; }
        public virtual Participantes Participantes1 { get; set; }
    }
}
